name: Git Pilot Sync

on:
  push:
    branches:
      - main
    paths:
      - templates/**

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Git Pilot
        uses: r3d-shadow/github-action-pilot@v0.1.1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          template_dir: templates
          state_file: templates/.git-pilot-state.json
          values: templates/values.yml

      - name: Commit updated state file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add templates/.git-pilot-state.json
          git commit -m "chore: update Git Pilot state file"
          git push